### ISSUE TITLE
[suggestion] add setFunctions like in phpScaner

### ISSUE THREAD

**Issue by jarodium** [php-gettext/JS-Scanner#2]
Hello, 

I'm using [https://github.com/guillaumepotier/gettext.js/](url) as a library for my translations.
I have wrapped it's gettext function into a _() like function ( for convenience and familiarity with php ), but this scanner can't seem to find it.
I think adding phpScanner's setFunctions method would solve this, helping to get translations to get scanned in every other js based translation library.

Thank you

**Comment by oscarotero** [comment]
The predefined functions are based in [JS-Translator](https://github.com/php-gettext/JS-Translator).

But you have `setFunctions()` to customize them, because both PHP-Scanner and JS-Scanner extends the same class [CodeScanner](https://github.com/php-gettext/Gettext/blob/master/src/Scanner/CodeScanner.php#L26)
